name: flutter_account_kit
description: A new flutter plugin project.
version: 0.5.0
author: Onyemaechi Okafor
homepage:

dependencies:
  flutter:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

dev_dependencies:
  flutter_test:
    sdk: flutter
    
# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: com.peerwaya.flutteraccountkit
    pluginClass: FlutterAccountKitPlugin
